namespace TownOfUs
{
    public enum CustomRPC
    {
        SetJester = 43,
        SetCouple,
        SetMayor,
        SetSheriff,
        SetEngineer,
        SetSwapper,
        SetShifter,
        SetInvestigator,
        SetTimeLord,
        SetMedic,
        SetSeer,
        SetMorphling,
        SetCamouflager,
        SetExecutioner,
        SetTarget,
        SetSpy,
        SetSnitch,
        SetMiner,
        SetSwooper,
        SetJanitor,
        SetAssassin,
        SetArsonist,
        SetAltruist,
        SetPhantom,
        SetButtonBarry,
        SetUndertaker,

        SetTorch,
        SetDiseased,
        SetFlash,
        SetTiebreaker,
        SetDrunk,
        SetBigBoi,

        SetCrewmate,
        SetImpostor,


        SoloImpWin,
        LoveWin,
        GlitchWin,
        ArsonistWin,
        PhantomWin,
        SoloImpLose,
        JesterLose,
        ExecutionerLose,
        ShifterLose,
        GlitchLose,
        ArsonistLose,
        PhantomLose,
        NobodyWins,

        JanitorClean,
        FixLights,
        EngineerFix,
        SetExtraVotes,
        SetSwaps,
        Shift,
        Protect,
        AttemptSound,
        Investigate,
        Rewind,
        RewindRevive,
        Morph,
        Camouflage,
        Mine,
        Swoop,
        Douse,
        Ignite,
        AltruistRevive,
        BarryButton,
        CatchPhantom,
        ForceSetPhantom,
        DragBody,
        DropBody,

        SetGlitch,
        BypassKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,
        KillDuringMeeting,

        ExecutionerToJester,


        Start,
        SyncCustomSettings,
        FixAnimation,
    }
}
